name: Build And Push Professional Profiles Docker Image To Docker Hub

on:
  pull_request:
    branches:
      - development
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest tag from Docker Hub
        id: get_latest_tag
        run: |
          tags=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.PROFILES_DEV_HUB_USERNAME }}/pro-files-server/tags?page_size=100 | jq -r '.results[].name')
          echo "All tags: $tags"
          
          latest_version=$(echo "$tags" | grep -E '^v[0-9]+$' | sort -V | tail -n 1)
          echo "Latest version: $latest_version"

          if [ -z "$latest_version" ]; then
            next_version="v1"
          else
            next_num=$(echo $latest_version | sed 's/v//')
            next_num=$((next_num + 1))
            next_version="v$next_num"
          fi

          echo "Next version: $next_version"
          echo "tag=$next_version" >> $GITHUB_OUTPUT

      - name: Build Docker Image with version and live tags
        run: |
          docker build -t ${{ secrets.PROFILES_DEV_HUB_USERNAME }}/pro-files-server:${{ steps.get_latest_tag.outputs.tag }} \
                       -t ${{ secrets.PROFILES_DEV_HUB_USERNAME }}/pro-files-server:live \
                       -f ProfessionalProfiles/Dockerfile .

      - name: Push Both Docker Image Tags to Docker Hub
        run: |
          docker login -u ${{ secrets.PROFILES_DEV_HUB_USERNAME }} -p ${{ secrets.PROFILES_DEV_HUB_SECRET }}
          docker push ${{ secrets.PROFILES_DEV_HUB_USERNAME }}/pro-files-server:${{ steps.get_latest_tag.outputs.tag }}
          docker push ${{ secrets.PROFILES_DEV_HUB_USERNAME }}/pro-files-server:live